name: Go Auto Build and Release (Chat App)

on:
  push:
    tags:
      - "v*.*.*"  # Triggers on version tags like v1.0.0

jobs:
  build:
    name: Build Server and Client
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [linux, windows, darwin]
        arch: [amd64, arm64]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.21

      - name: Build Server
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o server-${{ matrix.os }}-${{ matrix.arch }} ./server/server.go

      - name: Build Client
        run: |
          GOOS=${{ matrix.os }} GOARCH=${{ matrix.arch }} go build -o client-${{ matrix.os }}-${{ matrix.arch }} ./client/*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: binaries-${{ github.run_id }}
          path: |
            server-${{ matrix.os }}-${{ matrix.arch }}
            client-${{ matrix.os }}-${{ matrix.arch }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          files: artifacts/**
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

